[project]
name = "flask-frest"
version = "0.1.1"
description = "make your flask app become restful and modern"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "pydantic>=2.9.2",
]
